name: party_games_by_tdng
description: "Party Games by TDNG"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  signalr_core:
  http:
  shared_preferences:
  animations:
  google_fonts:
  dart_jsonwebtoken:
  envied: ^0.5.4+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9


flutter:
  uses-material-design: true
  assets:
    - images/
